version: "3.10"

services:
  neurogengpt:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "7861:7860"
      - "1338:1337"
    volumes:
      - ../config.json:/app/config.json
    env_file:
      - .env
